---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: pivotalservices/docker-concourse-cf-tools
    tag: "latest"

inputs:
- name: git-repo
- name: service-info

outputs:
- name: app-manifest-output

run:
  path: ./git-repo/acceptance/tasks/app-manifest-prep.sh
  