---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: pivotalservices/docker-concourse-cf-tools
    tag: "latest"

inputs:
- name: git-repo

outputs:
- name: service-info

run:
  path: ./git-repo/acceptance/tasks/create-service.sh
  